### ISSUE TITLE
Stacked Field in SimpleRepeatable

### ISSUE THREAD

**Issue by jjjrmy** [outl1ne/nova-simple-repeatable#29]
```php
SimpleRepeatable::make('Step Groups', 'step_groups', [
    Stack::make('Name', [
        Text::make('Name', 'name'),
        Slug::make('Slug')->from('Name'),
    ]),
    Textarea::make('Value'),
    Textarea::make('Default')->nullable()
])->stacked(),
```

This returns the error:
`Call to a member function all() on array`

**Comment by marttinnotta** [comment]
Hi!

First it would not make sense to put stack inside repeater field but other way around.
Second thing is that SimpleRepeatable just like any other Nova field (Trix, Markdown, KeyValue etc...) that has special display output will not work with Stack field.

If you need this to work I would suggest forking this package and tailor it for your own needs.

Good luck!
