### ISSUE TITLE
Can you release 1.5.0 with laravel 9 support?

### ISSUE THREAD

**Issue by keizah7** [outl1ne/nova-simple-repeatable#30]
I upgrading to laravel 9, and using nova 3. Can't use nova 4 for now

https://github.com/keizah7/nova-simple-repeatable/commit/8218f37e3523a2f5c03866cd1d56575191981f2b

**Comment by Tarpsvo** [comment]
What's stopping you from using Laravel 9 exactly?

**Comment by keizah7** [comment]
Problem solved
