### ISSUE TITLE
Store SimpleRepeatable as JSON attribute not working.

### ISSUE THREAD

**Issue by chirag-nandaniya** [outl1ne/nova-simple-repeatable#33]
I am using SimpleRepeatable under Flexible Content Layout(https://github.com/whitecube/nova-flexible-content). Its generates the fields but not able to save it successfully. I think issue is SimpleRepeatable not able to store under JSON attribute. 

Flexible::make('Sub Regions', 'sub_regions')
                    ->addLayout('Sub Region', 'sub_region', [
                        Text::make('Title'),
                        SimpleRepeatable::make('Charges', 'charges', [
                            Text::make('Weight From', 'weight_from')
                                ->required(true),
                            Text::make('Weight To', 'weight_to')
                                ->required(true),
                    ])
                    ->fullWidth()
                    ->button('Add Sub Region'),
            ]),

Able to create one JSON attribute and save SimpleRepeatable JSON under it? Here "Charges" attribute not generated.

**Comment by KasparRosin** [comment]
Make sure you are running the latest version.
Unable to re-produce.
