### ISSUE TITLE
Array to String Conversion

### ISSUE THREAD

**Issue by jeremiahsherrill** [outl1ne/nova-simple-repeatable#37]
I set up the field as json, but when I save I get Array to String Conversion

What am I missing

    public function fields(Request $request)
    {
        return [
            
            SimpleRepeatable::make('Vacation Days', 'vacation_days', [
                Text::make('Name', 'name')->sortable(),
                Date::make('Starting Date', 'starts_at'),
                Date::make('Ending Date', 'ends_at'),
            ])->canAddRows(true)->canDeleteRows(true)

        ];
    }

**Comment by Tarpsvo** [comment]
You might have to add $casts = ['vacation_days' => 'array'] to your model.

**Comment by jeremiahsherrill** [comment]
duh.... yes, that is correct.  I knew I was forgetting something.  Thanks
