### ISSUE TITLE
Psalm InvalidArgument error

### ISSUE THREAD

**Issue by StApostol** [outl1ne/nova-simple-repeatable#43]
In nova abstract field exists annotation 
```
/**
* @method static static make(mixed $name, string|\Closure|callable|object|null $attribute = null, callable|null $resolveCallback = null)
*/
```

I get error "Argument 3 of Outl1ne\NovaSimpleRepeatable\SimpleRepeatable::make expects callable|null" for next code
```
SimpleRepeatable::make('Images', 'images', [
    URL::make('Url'),
]),
```

**Comment by marttinnotta** [comment]
Hi!

Updated annotation accordingly, fix will be released with next version. 

Thank you and good luck!
