### ISSUE TITLE
jsonSerialize incompatible

### ISSUE THREAD

**Issue by renege** [outl1ne/nova-simple-repeatable#44]
Keep getting error: `Return type of Outl1ne\NovaSimpleRepeatable\Row::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/task/vendor/outl1ne/nova-simple-repeatable/src/Row.php on line 68`

**Comment by marttinnotta** [comment]
Hi

Added return type for `jsonSerialize` that is compatible with mixed type. This will be in next release.

Thank you and good luck!
