### ISSUE TITLE
* Missing on required fileds

### ISSUE THREAD

**Issue by TNDJX** [outl1ne/nova-simple-repeatable#45]
When setting fields as required * is missing from the field label.

Example: 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/57906002/232524365-c1b3c04d-94d8-41b2-9e03-dcfcbf44d803.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/57906002/232524477-ea63f035-b5c7-4d83-95fd-9e0bb1564fd1.png">

Field **Text** should have red * to indicate that field is required

**Comment by TNDJX** [comment]
I have also played around and only thing needed is that in FormField.vue we added something like this

```
<div
  v-for="(rowField, i) in fields"
  :key="i"
  class="nsr-font-bold nsr-text-90 nsr-text-md nsr-w-full nsr-ml-3 nsr-flex nsr-space-x-1"
  >
  <span>
    {{ rowField.name }}
  </span>
  <span v-if="rowField.required" class="nsr-text-red-500 nsr-text-sm">
    {{ __('*') }}
  </span>
```

I would open a PR but Its not letting me push to the branch I created

**Comment by marttinnotta** [comment]
Hi and thank you!

This will be available in the next release.
