### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by polaquim83** [outl1ne/nova-simple-repeatable#47]
Hi all,

How can set default value ?

Thanks in advance

**Comment by edmondtham** [comment]
Can try this
Text::make('Text')
->withMeta(['value' => 'Default Value']),

**Comment by marttinnotta** [comment]
Hi!

If you want to set default values then you can use [default value callback](https://nova.laravel.com/docs/4.0/resources/fields.html#default-values) but as far as I'm aware of this will set default value when creating new resource. This method won't work for update view.

Currently there is no way to add default values for simple repeatable itself and I think we are not planning to add one.
