### ISSUE TITLE
Multiple SimpleRepeatable on same page validation issue

### ISSUE THREAD

**Issue by Algeneralo** [outl1ne/nova-simple-repeatable#48]
I'm having multiple SimpleRepeatable fields on the same page and each one has a validation rules.
But the validation is only being applied for the first SimpleRepeatable field.

**Comment by marttinnotta** [comment]
Will look into this.

**Comment by marttinnotta** [comment]
Thank you for the feedback!

We have looked into this and hopefully this will make it into next release.
