### ISSUE TITLE
[Help wanted] [Possible-bug] How to work with nova-translatable

### ISSUE THREAD

**Issue by briavers** [outl1ne/nova-simple-repeatable#56]
I'm trying to make my repeater field translatable, but once i save it stays empty and gives a console error 

Packages used 
optimistdigital/nova-translatable: 1.12
outl1ne/nova-simple-repeatable: 1.4.3
laravel/nova: 3.32

Code 

Migration 
```php
Schema::table('projects', function (Blueprint $table) {
    $table->json("items")->nullable();
});
```

model

```php
 public $translatable = [
        'items',
    ];
```

nova-resource 
```php
 SimpleRepeatable::make(__('Bullet points'), 'items', [
                Text::make(__('Bullet point'), 'bullet_point'),
            ])->translatable(),
```

console Exception, and no items or item title to be found
<img width="1224" alt="image" src="https://github.com/outl1ne/nova-simple-repeatable/assets/26483622/4da66235-a33b-4eb3-b2ec-ed6538ce8d18">

**Comment by p-jrv** [comment]
Common use case would be calling `->translatable()` on a field inside the SimpleRepeatable not on the SimpleRepeatable itself:

` SimpleRepeatable::make(__('Bullet points'), 'items', [
                Text::make(__('Bullet point'), 'bullet_point')->translatable(),
            ]),`
